FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY .streamlit/ .streamlit/
COPY . .

EXPOSE 8501

ENV API_URL="http://backend:8000"

CMD ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]